version: "3.9"

services:
  app:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./out:/usr/share/nginx/html
    ports:
      - "8080:8080"